import { MotionConfig } from "framer-motion";
import Header from "@/components/Header";
import Hero from "@/components/Hero";
import SobreEspaco from "@/components/SobreEspaco";
import Beneficios from "@/components/Beneficios";
import Servicos from "@/components/Servicos";
import Equipe from "@/components/Equipe";
import CTASection from "@/components/CTASection";
import Contato from "@/components/Contato";
import Footer from "@/components/Footer";
const Index = () => <MotionConfig reducedMotion="user"><div id="inicio" className="min-h-screen bg-background"><a className="skip-link" href="#conteudo">Pular para o conteúdo</a><Header /><main id="conteudo" tabIndex={-1}><Hero /><SobreEspaco /><Beneficios /><Servicos /><Equipe /><CTASection /><Contato /></main><Footer /></div></MotionConfig>;
export default Index;
